# Site wide configuration

title: XMPP-IoT
description: "How XMPP can solve the IoT puzzle"
logo: 120x120.gif # 120x120 px default image used for Twitter summary card
teaser: 400x250.gif # 400x250 px default teaser image used in image archive grid
locale:
#url: //xmpp-iot.github.io
url: http://localhost:4000

# GSoC Blog

blog_name: GSoC 2015 Blog
blog_description: All posts related to XMPP IoT GSoC 2015 Project will be posted here.
#blog_url: //xmpp-iot.github.io/gsoc
blog_url: http://localhost:4000/gsoc

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
markdown: kramdown
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: "Joachim Lindborg"
  email: "joachim.lindborg@lsys.se"
  twitter: joachimlindborg
  google:
    ad-client: 
    ad-slot: 
  bio: 
  avatar: bio-photo.jpg # 160x160 px image for author byline
disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
